// examples/react-spa-app/my-app/src/App.js
/*
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Created using create-react-app: https://create-react-app.dev/
*/
import Logo from './logo.svg';
import './App.css';
import React, { useState, useEffect } from "react";

function App(props) {
  const [apiResult, setApiResult] = useState(null);
  useEffect(() => {
    fetch(props.backendUrl + "/api/hello", {
      method: "GET",
      // This is required for IAP support or sending a session cookie to the backend when it's 
      // in a different domain.
      credentials: "include",
    })
      .then((response) => response.text())
      .then((data) => {
        setApiResult(data);
        console.log(data);
      })
      .catch((error) => console.log(error));
  }, []);

  return (
    <div className="App">
      <header className="App-header">
        <h1 id="title-text">Cloud Foundation Fabric</h1>
        <h2 id="subtitle-text">React test app</h2>
        <Logo className="App-logo" alt="logo" />
        <p>
          Anything is possible at this URL. The backend says:
          <pre>
            {apiResult}
          </pre>
        </p>
      </header>
    </div>
  );
}

export default App;

// tools/bq-visualizer/src/app/app.component.ts
/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {Component, ViewChild} from '@angular/core';
import {GoogleAuthService} from './google-auth.service';



@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'BQ Visualiser';
  xxxisLoggedIn = false;
  constructor(private googleAuthService: GoogleAuthService) {
    this.googleAuthService.loginEvent.subscribe(
        (isloggedIn: boolean) => this.register_login(isloggedIn));

    //this.isLoggedIn = this.googleAuthService.isLoggedIn();
  }
  /* event handler to recognise a login or logout event has occurred */
  private register_login(what: boolean) {
    this.xxxisLoggedIn = what;
    //console.log('AppComponent::registered_login: ' + what)
  }
  public login() {
    //console.log('AppComponent::login calling googleAuthService.login')
    this.googleAuthService.login();
  }

  public logout() {
    console.log('AppComponent::logout calling googleAuthService.logout')

    this.googleAuthService.logout();
  }

  get isLoggedIn(){
    return this.googleAuthService.isLoggedIn();
  }
}

<!--
/*
 * Copyright (C) 2021 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
-->
<div class="header">
  <h1 class="header__title">BQ Visualiser</h1>
  <span class="flex-spacer"></span>
  <button mat-button [disabled]="this.isLoggedIn" (click)="login()">login</button>
  <button mat-button [disabled]="!this.isLoggedIn" (click)="logout()">logout</button>
  <div id=gloginBtn></div>
  <a mat-button href="/terms">Terms</a>
</div>
<div class="main">
  <router-outlet></router-outlet>
</div>
